"""Agregar metodo_pago a Venta

Revision ID: 1b8ebdeae5ca
Revises: c293d2e3caba
Create Date: 2025-05-21 11:20:28.629803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8ebdeae5ca'
down_revision = 'c293d2e3caba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
