"""Traer campo producto en venta

Revision ID: c293d2e3caba
Revises: d66610bb810d
Create Date: 2025-05-09 22:55:22.798319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c293d2e3caba'
down_revision = 'd66610bb810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('producto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
