"""Traer campo producto en venta

Revision ID: d66610bb810d
Revises: a1d5d9ce4823
Create Date: 2025-05-09 22:50:48.610079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66610bb810d'
down_revision = 'a1d5d9ce4823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('producto')

    # ### end Alembic commands ###
